### PR TITLE
feat: Add user metadata methods to api v2

### PR DESCRIPTION
**Pull request by mzaniolo**
close: #17

### CODE REVIEW

**Comment by sirewix** [comment]
We needed to do some hackery in v1 grpc client, is it taken care of here? Or maybe it's not needed, just making sure

https://github.com/famedly/zitadel-rust-client/blob/cd653fad9f722e3021aa0cd3250ce9be9f30be0c/src/v1/mod.rs#L479-L486

**Comment by mzaniolo** [comment]
> We needed to do some hackery in v1 grpc client, is it taken care of here? Or maybe it's not needed, just making sure
> 
> https://github.com/famedly/zitadel-rust-client/blob/cd653fad9f722e3021aa0cd3250ce9be9f30be0c/src/v1/mod.rs#L479-L486

Well, depends on the behavior we want. When we try to get the metadata that doesn't exist the response from server is 404 and message containing `QUERY-Rph32`. Today the code only returns an Err containing the http status and message. So, there is no way to tell, without reading the msg, what was the problem, if the user doesn't exist or if the metadata key doesn't exist or something else.
This is a problem for all methods, we don't have proper error here and the docs are not very clear about the errors. Should we start to create our own error and try to map the zitadel errors to them?

**Comment by emgrav** [comment]
Yes, I would say we should. This would be a substantial task though, so it would make sense to start with the ones we need, like this one since we need to differentiate between metadata errors. Regrettably, I don't think there is any better documentation than just finding these error codes in the source code. I can ask them if they have any overview of error codes

**Comment by mzaniolo** [comment]
> Yes, I would say we should. This would be a substantial task though, so it would make sense to start with the ones we need, like this one since we need to differentiate between metadata errors. Regrettably, I don't think there is any better documentation than just finding these error codes in the source code. I can ask them if they have any overview of error codes

Creating specific errors will take some rework of the request code. I would propose to merge this PR without it and I make a new one only with the changes necessary for dealing with the errors and some tests. What do you think?

**Comment by emgrav** [comment]
Sure, that would work. It's probably not something we need to implement right away. I will open an issue

**Review by sirewix — APPROVED** [review]

**Pull request merged**
